config:
  credentials: []
  project_repos:
    git.scc.kit.edu/px5501/Mss:
      branch: main
      repo: https://git.scc.kit.edu/px5501/Mss
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/px5501/Mss git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-periwinkle-maltese.sh
        container: qc.acc_lousy-goldenrod-angora
  QC.Doc:
    repos:
      git.scc.kit.edu/px5501/Mss find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-salmon-deer.sh
        container: qc.doc_zippy-red-turtle
      git.scc.kit.edu/px5501/Mss git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-myrtle-slug.sh
        container: qc.doc_chewy-olivine-moth
      git.scc.kit.edu/px5501/Mss markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-auburn-eagle.sh
        container: qc.doc_beady-lavender-walrus
  QC.Lic:
    repos:
      git.scc.kit.edu/px5501/Mss licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-puce-tarantula.sh
        container: qc.lic_geeky-silver-dunker
  QC.Sec:
    repos:
      git.scc.kit.edu/px5501/Mss bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-apricot-impala.sh
        container: qc.sec_surly-pink-magpie
  QC.Sty:
    repos:
      git.scc.kit.edu/px5501/Mss flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ready-emerald-goose.sh
        container: qc.sty_grumpy-puce-manatee
  QC.Ver:
    repos:
      git.scc.kit.edu/px5501/Mss get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-sangria-civet.sh
        container: qc.ver_woolly-cinnabar-akbash
timeout: 5400
