config:
  credentials: []
  project_repos:
    git.scc.kit.edu/px5501/Mss:
      branch: main
      repo: https://git.scc.kit.edu/px5501/Mss
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/px5501/Mss git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-carmine-whale.sh
        container: qc.acc_freaky-firebrick-squirt
  QC.Doc:
    repos:
      git.scc.kit.edu/px5501/Mss find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-charcoal-schnauzer.sh
        container: qc.doc_frumpy-tan-dalmatian
      git.scc.kit.edu/px5501/Mss git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-thistle-buzzard.sh
        container: qc.doc_lanky-saffron-setter
      git.scc.kit.edu/px5501/Mss markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-grey-sloth.sh
        container: qc.doc_jumpy-malachite-collie
  QC.Lic:
    repos:
      git.scc.kit.edu/px5501/Mss licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-plum-zonkey.sh
        container: qc.lic_flimsy-gamboge-bison
  QC.Sec:
    repos:
      git.scc.kit.edu/px5501/Mss bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-alizarin-mist.sh
        container: qc.sec_cozy-razzmatazz-zebra
  QC.Sty:
    repos:
      git.scc.kit.edu/px5501/Mss flake8:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-mustard-greyhound.sh
        container: qc.sty_homely-wheat-buzzard
  QC.Ver:
    repos:
      git.scc.kit.edu/px5501/Mss get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-khaki-lobster.sh
        container: qc.ver_crabby-seashell-wasp
timeout: 5400
