config:
  credentials: []
  project_repos:
    git.scc.kit.edu/px5501/Mss:
      branch: main
      repo: https://git.scc.kit.edu/px5501/Mss
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/px5501/Mss git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-auburn-albatross.sh
        container: qc.acc_sleepy-wisteria-turkey
  QC.Doc:
    repos:
      git.scc.kit.edu/px5501/Mss find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-turquoise-chinook.sh
        container: qc.doc_gloppy-blue-stingray
      git.scc.kit.edu/px5501/Mss git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-magenta-barracuda.sh
        container: qc.doc_pretty-purple-cow
      git.scc.kit.edu/px5501/Mss markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-mauve-bee.sh
        container: qc.doc_paltry-crimson-rattlesnake
  QC.Lic:
    repos:
      git.scc.kit.edu/px5501/Mss licensee:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-malachite-flounder.sh
        container: qc.lic_flimsy-goldenrod-shrimp
  QC.Sec:
    repos:
      git.scc.kit.edu/px5501/Mss bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-carmine-lizard.sh
        container: qc.sec_homely-sangria-clam
  QC.Sty:
    repos:
      git.scc.kit.edu/px5501/Mss flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-goldenrod-caterpillar.sh
        container: qc.sty_lumpy-indigo-affenpinscher
  QC.Ver:
    repos:
      git.scc.kit.edu/px5501/Mss get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-rose-monster.sh
        container: qc.ver_blurry-heliotrope-burmese
timeout: 5400
