config:
  credentials: []
  project_repos:
    git.scc.kit.edu/px5501/Mss:
      branch: main
      repo: https://git.scc.kit.edu/px5501/Mss
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/px5501/Mss git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-celadon-starfish.sh
        container: qc.acc_snippy-vermilion-sheepdog
  QC.Doc:
    repos:
      git.scc.kit.edu/px5501/Mss find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-turquoise-dolphin.sh
        container: qc.doc_muggy-heliotrope-coati
      git.scc.kit.edu/px5501/Mss git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cornflower-blue.sh
        container: qc.doc_lovely-linen-avocet
      git.scc.kit.edu/px5501/Mss markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-rust-seahorse.sh
        container: qc.doc_snazzy-asparagus-forest
  QC.Lic:
    repos:
      git.scc.kit.edu/px5501/Mss licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-chestnut-moth.sh
        container: qc.lic_messy-khaki-raccoon
  QC.Sec:
    repos:
      git.scc.kit.edu/px5501/Mss bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-linen-burmese.sh
        container: qc.sec_pasty-xanthic-burmese
  QC.Sty:
    repos:
      git.scc.kit.edu/px5501/Mss flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-chartreuse-husky.sh
        container: qc.sty_skinny-wheat-pig
  QC.Ver:
    repos:
      git.scc.kit.edu/px5501/Mss get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-rust-rabbit.sh
        container: qc.ver_lumpy-copper-hyena
timeout: 1800
