config:
  credentials: []
  project_repos:
    git.scc.kit.edu/px5501/Mss:
      branch: main
      repo: https://git.scc.kit.edu/px5501/Mss
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/px5501/Mss git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-blue-grasshopper.sh
        container: qc.acc_lovely-saffron-dolphin
  QC.Doc:
    repos:
      git.scc.kit.edu/px5501/Mss find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-razzmatazz-bongo.sh
        container: qc.doc_scanty-cinnabar-woodlouse
      git.scc.kit.edu/px5501/Mss git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-auburn-cattle.sh
        container: qc.doc_greasy-olive-cassowary
      git.scc.kit.edu/px5501/Mss markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-chartreuse-fousek.sh
        container: qc.doc_pretty-blue-moth
  QC.Lic:
    repos:
      git.scc.kit.edu/px5501/Mss licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-buff-husky.sh
        container: qc.lic_cheeky-olive-camel
  QC.Sec:
    repos:
      git.scc.kit.edu/px5501/Mss bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-malachite-bulldog.sh
        container: qc.sec_beady-corn-bee
  QC.Sty:
    repos:
      git.scc.kit.edu/px5501/Mss flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cornflower-fowl.sh
        container: qc.sty_gimpy-coral-cheetah
  QC.Ver:
    repos:
      git.scc.kit.edu/px5501/Mss get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cerulean-eagle.sh
        container: qc.ver_silly-sepia-meerkat
timeout: 5400
